server:
  port: 8080

spring:
  application:
    name: classroom-service
  profiles:
    active: @spring.profiles.active@

management:
  endpoint:
    health:
      show-details: always   # luôn hiển thị chi tiết
      show-components: always # hiển thị cả từng component con
  endpoints:
    web:
      exposure:
        include: '*'
#        include: health,info,metrics,prometheus